language: ruby
rvm:
- 2.1
install: gem install jekyll html-proofer
script: jekyll build && htmlproof ./_site --href-ignore http://www.linkedin.com/in/lcottereau/fr --check-html

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
